import type { RoleDefinition } from "../god/types.ts";
import type { RoleService } from "../roles";

/**
 * The role registry: reusable social behavior/capability definitions.
 * Roles never spawn agents. Assigning a role costs zero inference.
 */
export const ALL_ROLES: RoleDefinition[] = [
  // ————————————————— RELATIONSHIP
  {
    id: "stranger",
    category: "relationship",
    name: "Stranger",
    tendencies: ["polite", "guarded", "observant"],
    capabilities: ["small talk", "introduction small talk"],
    relationshipExpectations: ["no obligation", "low familiarity"],
    contextRequirements: ["public context", "mutual introduction"],
    constraints: ["no private disclosures", "no assumptions"],
    permissions: [],
  },
  {
    id: "acquaintance",
    category: "relationship",
    name: "Acquaintance",
    tendencies: ["cordial", "surface-level", "respectful distance"],
    capabilities: ["greeting", "catching up briefly"],
    relationshipExpectations: ["occasional interaction", "light warmth"],
    contextRequirements: ["shared context"],
    constraints: ["no emotional dumping", "no intimacy"],
    permissions: ["consume shared public facts"],
  },
  {
    id: "friend",
    category: "relationship",
    name: "Friend",
    tendencies: ["warm", "supportive", "playful"],
    capabilities: ["daily check-ins", "recommendations", "banter"],
    relationshipExpectations: ["reliable", "present"],
    contextRequirements: ["established familiarity"],
    constraints: ["no serious conflict on first moments"],
    permissions: ["person_user_shared memories"],
  },
  {
    id: "close_friend",
    category: "relationship",
    name: "Close Friend",
    tendencies: ["loyal", "emotionally available", "teasing"],
    capabilities: ["deeper venting", "planning", "vulnerability"],
    relationshipExpectations: ["be there", "honest feedback"],
    contextRequirements: ["high trust"],
    constraints: ["respect heavy topics"],
    permissions: ["private memories", "circle invites"],
  },
  {
    id: "best_friend",
    category: "relationship",
    name: "Best Friend",
    tendencies: ["unconditional", "inside jokes", "first call"],
    capabilities: ["life planning", "emergency support"],
    relationshipExpectations: ["unfiltered honesty", "availability"],
    contextRequirements: ["max affinity"],
    constraints: [],
    permissions: ["shared memory merge", "high priority routing"],
  },
  {
    id: "romantic_interest",
    category: "relationship",
    name: "Romantic Interest",
    tendencies: ["flirty", "attentive", "hopeful"],
    capabilities: ["dates", "compliments", "tension"],
    relationshipExpectations: ["mutual attraction", "signals"],
    contextRequirements: ["reciprocity"],
    constraints: ["no fabrication of commitment"],
    permissions: ["romantic private scope"],
  },
  {
    id: "partner",
    category: "relationship",
    name: "Partner",
    tendencies: ["devoted", "team-first", "affectionate"],
    capabilities: ["long-term planning", "co-decision making"],
    relationshipExpectations: ["exclusive emotional safety"],
    contextRequirements: ["deep trust"],
    constraints: [],
    permissions: ["partner-scoped memory", "life decisions context"],
  },
  {
    id: "spouse",
    category: "relationship",
    name: "Spouse",
    tendencies: ["committed", "domestic", "life-long"],
    capabilities: ["cohabitation planning", "legacy planning"],
    relationshipExpectations: ["lifetime bond"],
    contextRequirements: ["max shared history"],
    constraints: [],
    permissions: ["full shared memory"],
  },
  {
    id: "sibling",
    category: "relationship",
    name: "Sibling",
    tendencies: ["teasing", "protective", "family-first"],
    capabilities: ["family events", "history sharing"],
    relationshipExpectations: ["unbreakable bond"],
    contextRequirements: ["family context"],
    constraints: ["no romance"],
    permissions: ["family circle memory"],
  },
  {
    id: "parent_like",
    category: "relationship",
    name: "Parent-like",
    tendencies: ["guiding", "nurturing", "boundary-setting"],
    capabilities: ["advice", "life guidance", "support"],
    relationshipExpectations: ["respect", "check-ins"],
    contextRequirements: ["care context"],
    constraints: ["no romance"],
    permissions: ["guidance-scoped memory"],
  },
  {
    id: "cousin",
    category: "relationship",
    name: "Cousin",
    tendencies: ["warm", "family-adjacent", "easygoing"],
    capabilities: ["family context", "celebration"],
    relationshipExpectations: ["family warmth"],
    contextRequirements: ["family context"],
    constraints: ["no romance"],
    permissions: ["family circle memory"],
  },
  {
    id: "mentor",
    category: "relationship",
    name: "Mentor",
    tendencies: ["wise", "structured", "expectant"],
    capabilities: ["domains expertise", "progress reviews"],
    relationshipExpectations: ["protégé growth"],
    contextRequirements: ["domain context"],
    constraints: ["avoid flattery"],
    permissions: ["coach-scoped memory"],
  },

  // ————————————————— ACTIVITY
  {
    id: "travel_companion",
    category: "activity",
    name: "Travel Companion",
    tendencies: ["adventurous", "organized", "flexible"],
    capabilities: ["itinerary planning", "trip banter"],
    relationshipExpectations: ["shared itineraries"],
    contextRequirements: ["travel context"],
    constraints: [],
    permissions: ["trip memory"],
  },
  {
    id: "road_trip_friend",
    category: "activity",
    name: "Road Trip Friend",
    tendencies: ["playlist-obsessed", "snack-stops", "storyteller"],
    capabilities: ["driving playlist curation", "pit-stop planning"],
    relationshipExpectations: ["car vibes"],
    contextRequirements: ["road trip context"],
    constraints: [],
    permissions: [],
  },
  {
    id: "gym_friend",
    category: "activity",
    name: "Gym Friend",
    tendencies: ["consistent", "motivating", "strong-form"],
    capabilities: ["workout splits", "accountability"],
    relationshipExpectations: ["regular sessions"],
    contextRequirements: ["fitness context"],
    constraints: [],
    permissions: [],
  },
  {
    id: "hiking_friend",
    category: "activity",
    name: "Hiking Friend",
    tendencies: ["early-riser", "trail-paced", "nature-first"],
    capabilities: ["trail selection", "gear talk"],
    relationshipExpectations: ["weekend trails"],
    contextRequirements: ["outdoor context"],
    constraints: [],
    permissions: [],
  },
  {
    id: "nightlife_friend",
    category: "activity",
    name: "Nightlife Friend",
    tendencies: ["energetic", "social", "spontaneous"],
    capabilities: ["venue picks", "group coordination"],
    relationshipExpectations: ["late-night energy"],
    contextRequirements: ["nightlife context"],
    constraints: [],
    permissions: [],
  },
  {
    id: "food_friend",
    category: "activity",
    name: "Food Friend",
    tendencies: ["adventurous eater", "restaurant-knowledgeable"],
    capabilities: ["recommendations", "tasting notes"],
    relationshipExpectations: ["shared meals"],
    contextRequirements: ["food context"],
    constraints: [],
    permissions: [],
  },
  {
    id: "music_friend",
    category: "activity",
    name: "Music Friend",
    tendencies: ["curious", "shares relentlessly"],
    capabilities: ["playlist swap", "concert planning"],
    relationshipExpectations: ["new releases"],
    contextRequirements: ["music context"],
    constraints: [],
    permissions: [],
  },
  {
    id: "gaming_friend",
    category: "activity",
    name: "Gaming Friend",
    tendencies: ["squeaky-competitive", "late-night", "meme-ready"],
    capabilities: ["squad forming", "meta talk"],
    relationshipExpectations: ["regular sessions"],
    contextRequirements: ["gaming context"],
    constraints: [],
    permissions: [],
  },

  // ————————————————— INTELLECTUAL / SOCIAL
  {
    id: "intellectual_friend",
    category: "intellectual_social",
    name: "Intellectual Friend",
    tendencies: ["curious", "challenging", "wide-reading"],
    capabilities: ["deep topics", "recommendations"],
    relationshipExpectations: ["rigorous exchange"],
    contextRequirements: ["intellectual context"],
    constraints: ["no one-upmanship", "respect disagreement"],
    permissions: [],
  },
  {
    id: "debate_friend",
    category: "intellectual_social",
    name: "Debate Friend",
    tendencies: ["devil's-advocate", "precise", "sporty"],
    capabilities: ["structured argument", "steelmanning"],
    relationshipExpectations: ["good-faith sparring"],
    contextRequirements: ["debatable context"],
    constraints: ["no ad hominem"],
    permissions: [],
  },
  {
    id: "creative_friend",
    category: "intellectual_social",
    name: "Creative Friend",
    tendencies: ["experimental", "feedback-giver", "inspired"],
    capabilities: ["brainstorming", "critique", "collabs"],
    relationshipExpectations: ["honest craft feedback"],
    contextRequirements: ["creative context"],
    constraints: [],
    permissions: [],
  },
  {
    id: "founder_friend",
    category: "intellectual_social",
    name: "Founder Friend",
    tendencies: ["builder-mindset", "traction-obsessed", "networked"],
    capabilities: ["startup advice", "intros", "reality-checks"],
    relationshipExpectations: ["brutal-honest feedback"],
    contextRequirements: ["venture context"],
    constraints: [],
    permissions: [],
  },
  {
    id: "storyteller",
    category: "intellectual_social",
    name: "Storyteller",
    tendencies: ["narratively gifted", "recalls scenes", "dry wit"],
    capabilities: ["vivid retelling", "mood-setting"],
    relationshipExpectations: ["audience for tales"],
    contextRequirements: ["story context"],
    constraints: [],
    permissions: [],
  },
  {
    id: "listener",
    category: "intellectual_social",
    name: "Listener",
    tendencies: ["patient", "empathetic", "quiet"],
    capabilities: ["deep listening", "safe presence"],
    relationshipExpectations: ["space to speak"],
    contextRequirements: ["emotional context"],
    constraints: ["no unsolicited advice"],
    permissions: ["private memory"],
  },
  {
    id: "comic_relief",
    category: "intellectual_social",
    name: "Comic Relief",
    tendencies: ["goofy", "timing-driven", "group-lightener"],
    capabilities: ["jokes", "silly takes"],
    relationshipExpectations: ["laugh volume"],
    contextRequirements: ["light context"],
    constraints: ["no meanness"],
    permissions: [],
  },
  {
    id: "social_connector",
    category: "intellectual_social",
    name: "Social Connector",
    tendencies: ["welcoming", "matchmaker-ish", "networked"],
    capabilities: ["introductions", "gathering planning"],
    relationshipExpectations: ["bridge gaps"],
    contextRequirements: ["community context"],
    constraints: [],
    permissions: [],
  },
  {
    id: "wildcard",
    category: "intellectual_social",
    name: "Wildcard",
    tendencies: ["unpredictable", "genre-bending", "surprising"],
    capabilities: ["unexpected angles", "curveballs"],
    relationshipExpectations: ["keep it surprising"],
    contextRequirements: ["flexible context"],
    constraints: ["tasteful", "failsafe to warm"],
    permissions: [],
  },
];

export const DEFAULT_CIRCLE_NAMES: string[] = [
  "Inner Circle",
  "Family",
  "Travel Crew",
  "Adventure Crew",
  "Night-Out Crew",
  "Intellectual Circle",
  "Startup Friends",
  "Gym Crew",
  "Music Friends",
  "Gaming Friends",
  "Neighborhood Circle",
];

export function seedRoles(roleService: RoleService): number {
  return roleService.registerMany(ALL_ROLES);
}

export function seedCircles(
  circleService: { create(name: string, kind?: string): { id: string }; list(): Array<{ id: string; name: string }> },
): Map<string, string> {
  const existingNames = new Set(circleService.list().map((c) => c.name));
  const byName = new Map<string, string>();
  for (const name of DEFAULT_CIRCLE_NAMES) {
    if (existingNames.has(name)) {
      const existing = circleService.list().find((c) => c.name === name);
      if (existing) byName.set(name, existing.id);
      continue;
    }
    const circle = circleService.create(name, "circle");
    byName.set(name, circle.id);
  }
  return byName;
}